apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: hpa
spec: 
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: nginx-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 7
