---

apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deploy
   namespace: hpa
spec: 
  selector: 
     matchLabels:
       run: app
  template: 
    metadata: 
      labels:
        run: app
    spec: 
      containers: 
      - name: nginx-con
        image: nginx:latest
        resources: 
           limits:
              cpu: "100m"
           requests:
              cpu: "100m"
        ports:
        - containerPort: 80
        

---

apiVersion: v1
kind: Service
metadata: 
   name: nginx-service
   namespace: hpa
   labels:
     run: app
spec: 
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector: 
    run: app
  type: NodePort
  
